# Generated by Django 4.1.6 on 2024-10-02 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("description", models.CharField(max_length=50)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("to_do", "to do"),
                            ("in_progress", "in  progress"),
                            ("done", "done"),
                            ("archived", "archived"),
                        ],
                        max_length=50,
                    ),
                ),
                ("dead_line", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
